### useBalance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}


### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "87e413825fba4dd89992ee2b3775ad10",
  "accountNumber": "1000000002",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/58218ca175b24bc08afe6bc05fe64d41
